os:
- linux
- osx
language: cpp
env:
  global:
  - secure: AXHFIafTmbGDsHD3mUVj5a4I397DQjti/WoqAJGUp2PglxTcc04BwxZ9Z+xLuf5N2Hs5r9ojAJLT8OGxJCLBDXzneQTNSqXbFuYSLbqrEAiIRlA9eRIotWCg+wYcO+5e8MKX+cHVKwiIWasUB21AtCdq6msh6Y3pUshZp212VPg=
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - xorg-dev
    - lib32stdc++6
install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-compress.sh"
deploy:
  provider: releases
  api_key:
    secure: f6FDgxLRb0ccEFIwD9BQvS06bnuTX1LJapnTOH7QSIACK7/pIVjut8hRMRW0THW7HL3bzcs/WZMLrmWtJGsc2CQ94LrkT9ZwZ325amnn6z3x+n3nIrkknYsHhUagXTw+Ygc7bM43l1iQxxXPNLQrmFUeT3/ITL/PlH/BZbMJR7aa2VmXWOxYI2ubkwX4EVQ/bHY/HX8TiUXIYYh4eT5OR0lYYzEvGfddcE6+h1J/iAhdcwtVZizfRlrNlpHyYUHX5nPoPAlrr7BtINeZHJeH10Og8mEWw8PtVspntyffhv2lyIAiFTn1FCayIs7mBupJFelmcxG5LVQ27NjCjXwnZnzfQZGsBOZtWL6mRhuneOpYuVcsy4xmu56xnX/K7E6m/gWG86iJBPAREjaJJ3Oj3zqX3vl6OefAbyGxuSHH9r1/l0cjP4pyf7wHp6vi0J0De5Ha7lUEn9cKwoVJAyUqKm5s81XTUQOOv6X2Wl1dVTChgrbybjI5eWZd/K3vba5+ldnxgMzQG0woaCGMAP9LTy77Tq5fMs9/SRg2IP68pCszvkoQdc2n2uWbUklokj5U2Z1rReKJKFBceIZLH/PQ/56MtGNVkfnp3a+/9Wc0jmTMoKHctEl2IiJWClwJl7rFeeFQgaqqihsGG5L/k1WxRN6u5jTwjvXgdHYWHAiNxlY=
  file: citra*.tar.xz
  file_glob: true
  skip_cleanup: true
notifications:
  email: false
branches:
  only:
  - master
